# docker-compose.yml
services:
  web:
    build: .
    container_name: php_web
    ports:
      - "8089:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always
  db:
    image: mysql:8.0
    container_name: php_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # Add this phpmyadmin service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: php_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    restart: always

volumes:
  mysql_data: